In [2]:
 import numpy as np

In [5]:
arr1=np.array([1,3,4,5,56]*8)
print(arr1)

[ 1  3  4  5 56  1  3  4  5 56  1  3  4  5 56  1  3  4  5 56  1  3  4  5
 56  1  3  4  5 56  1  3  4  5 56  1  3  4  5 56]


In [7]:
arr2=np.array([2,3,4],ndmin=17)
print(arr2)

[[[[[[[[[[[[[[[[[2 3 4]]]]]]]]]]]]]]]]]


In [11]:
arr3=np.array([[67,6],[34,567],[45,65]],ndmin=10)
print(arr3)

[[[[[[[[[[ 67   6]
         [ 34 567]
         [ 45  65]]]]]]]]]]


In [29]:
arr4=np.array([9,23,3,45,656,67,6],ndmin=10)
arr5=np.array([23,34,45,45,56,7,6],ndmin=10)
print(arr4+arr5)
print(arr4-arr5)

[[[[[[[[[[ 32  57  48  90 712  74  12]]]]]]]]]]
[[[[[[[[[[-14 -11 -42   0 600  60   0]]]]]]]]]]


In [30]:
arr4.shape
# arr4.size
arr5.shape
#  arr5.size

(1, 1, 1, 1, 1, 1, 1, 1, 1, 7)

In [31]:
np.min(arr4,axis=1)




array([[[[[[[[[  9,  23,   3,  45, 656,  67,   6]]]]]]]]])

In [34]:
np.max(arr4,axis=1)

array([[[[[[[  9,  23,   3,  45, 656,  67,   6]]]]]]])

In [ ]:
np.arr4